name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    strategy:
      matrix:
        project: [backend, frontend]
        node-version: [22.x] # Specify Node.js 22
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: ${{ matrix.project }}/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: ./${{ matrix.project }}
      - name: Execute tests
        run: |
          if [ "${{ matrix.project }}" = "frontend" ]; then
            yarn test:ci
          else
            yarn test
          fi
        working-directory: ./${{ matrix.project }}